#!/bin/sh
# Transplant each service's ./supervise/ to /run/runit/${sv_name}/, to avoid
# filesystem writes in /etc/. This only needs to happen once per service.

runsv_runtime_dir="/run/runit"
SVDIR="/etc/service"

for sv_fullpath in "${SVDIR}"/*; do
    test -d "${sv_fullpath}" || continue # not a dir? weird, best not to touch it

    if [ ! -L "${sv_fullpath}/supervise" ]; then
        rm -rfv "${sv_fullpath}/supervise" &&
        ln -Trs "${runsv_runtime_dir}/${sv_fullpath##*/}" "${sv_fullpath}/supervise"
    fi

    test -d "${sv_fullpath}/log" || continue # log dir is optional

    if [ ! -L "${sv_fullpath}/log/supervise" ]; then
        rm -rfv "${sv_fullpath}/log/supervise" &&
        ln -Trs "${runsv_runtime_dir}/log.${sv_fullpath##*/}" "${sv_fullpath}/log/supervise"
    fi
done
