Some ebuilds for Gentoo
=======================

These are my packages for things that:

* aren't in the main Gentoo tree at all,
* aren't as up-to-date as I'd like there,
* aren't maintained to a sufficient standard in the main tree.

Keywords are all `~amd64 ~x86` because I don't run Gentoo on anything else yet,
but if you'd like me to add other arches just ask.

Installing
----------

You should already know how this works, but here's a reminder…

Put this (or whatever's appropriate for your system) in `/etc/portage/repos.conf`,
then do `emerge --sync flussence`:

    [flussence]
    location = /var/db/repositories/flussence
    sync-type = git
    sync-uri = https://gitlab.com/flussence/overlay.git

Contents
--------
N.B.: Anything not listed here is considered *very experimental*! Or I forgot to add it.

`app-crypt/signify` — https://github.com/aperezdc/signify[OpenBSD Signify]::
Signify is a strong cryptographic signature tool that fits on a floppy disk, with public
keys that fit in 140 characters, and a manpage that fits on one screen.

`dev-perl/Crypt-LE` — http://search.cpan.org/dist/Crypt-LE[Crypt::LE]::
A Perl 5 ACME/Let's Encrypt client with lightweight dependencies.
Not the most user-friendly option, but it gets the job done.
Current version supports ECC certs, wildcards and ACME API v2.

`dev-vcs/src` — https://gitlab.com/esr/src[Simple Revision Control]::
A version control tool suitable for all those loose scripts you have lying around.

`games-action/minecraft` — Java launcher for Minecraft::
Convenience ebuild that keeps the Minecraft launcher up to date for you.
Does not buy the game for you. Do that yourself.

`games-engines/odamex` — https://odamex.net[Odamex DOOM sourceport]::
Retro first-person shooter. This ebuild is written from scratch.

`games-fps/ut2004-*` — UT2004 binaries and map packs via IPFS::
+
--
The mirror URLs for these have proved chronically unreliable, so these ebuilds use IPFS.
You'll need to configure your local IPFS node as a distfiles mirror,
by adding a line like `ipfs http://localhost:8080` to `/etc/portage/mirrors`.

*Help preserving these files (and more) would be appreciated.*
The Manifest files contain additional SHA1 hashes (should be easily web searchable),
and the IPFS hashes were generated using 0.4.15 defaults: `--hash sha2-256 --chunker size-262144`.

Obviously, this doesn't contain the base game data files, which are required.
You still need to buy the disc and install `games-fps/ut2004-data::gentoo` for that.
--

`games-server/minecraft-server` — minecraft-server ebuilds::
+
--
These are heavily modified derivatives of the ebuilds in the
http://git.overlays.gentoo.org/gitweb/?p=proj/java.git;a=summary[Java overlay]
(which hadn't been updated since around 1.4).

The OpenRC initscript was removed and versions are individually slotted;
it's up to you to decide how you want to run a game server.
--

`games-util/friidump` — https://github.com/bradenmcd/friidump[GameCube/Wii disc ripping utility]::
Allows a computer with the right kind of drive to rip these discs natively.
Turns out I had one of those, so I made an ebuild out of it.
It crashes at runtime but maybe it'll work for someone else.

`gnome-extra/gucharmap` — GTK+2 version of gucharmap::
+
--
The last released GTK+2 version of gucharmap, patched to recognise new Unicode characters.
Contains far fewer dependencies than the current GNOME 3 version forces upon you,
and is more useful than `kde-apps/kcharselect` (17.12 still doesn't support font fallbacks!)

Make sure to install this as `gnome-extra/gucharmap::flussence` (i.e. with the repo ID),
or else the higher version number of the GTK+3 one will override it.
You may need to run `emerge --deselect gnome-extra/gucharmap` first if you have it already.
--

`media-libs/libopenmpt` — https://lib.openmpt.org[OpenMPT playback library]::
`media-plugins/audacious-openmpt` — https://github.com/cspiegel/audacious-openmpt[Audacious
libopenmpt plugin]::
A modern replacement for modplug and mikmod.
Much wider format support, more accurate playback, and better security upkeep.

`media-sound/audacious` — https://audacious-media-player.org/[Audacious Media Player]::
+
--
Gentoo's ebuilds for this have been bitrotting for over half a decade.
These are current versions, and I bothered to read the build scripts and get the dependencies right.

You can build and run this using any combination of the GTK+2, Qt5 or DBus interfaces.
Yes, you can have a completely CLI-controlled headless Audacious if you want.
--

`media-video/obs-studio` — https://github.com/jp9000/obs-studio[OBS Studio]::
Builds OBS from Git.
Probably has too many `USE` flags, but it works and does what I need from it.
You can even build it with no GUI at all, if you're into that sort of thing.

`net-news/quiterss` — https://quiterss.org[QuiteRSS]::
This is the last version before “HiDPI” support was added,
which can't be turned off and wastes too much screen space for me.

`sys-process/runit` — http://smarden.org[An init system you can trust]::
+
--
If you don't want systemd and OpenRC's recent developments worry you,
consider Taking A Third Option. Like this one.

This package is a hard fork of whatever was in the Gentoo tree years ago,
which was full of unfixed bugs and didn't have a responsible maintainer.
It does things slightly differently, so familiarise yourself before use; qlist is your friend.

For replacements to some OpenRC initscripts, take a look at
https://gitlab.com/flussence/runit-scripts[my runit-scripts repository].
At some time in the distant future I plan to drop the OpenRC dep for something new.
If that happens I'll give you plenty of advance warning.
--

`x11-libs/gtk+:3` — debloated Gtk+3
Contains a NetBSD patch which makes DBus (and auto-spawning of hidden DBus processes) optional.
Patch is from https://forums.gentoo.org/viewtopic-p-8245612.html#8245612

`x11-misc/compton` — yshui's compton fork
Upstream is more or less dead, and this has tons of fixes.

Copyright
---------

Due to limitations in the QA tool used, ebuild headers have to carry a GPL2-only statement.
For files *not* containing a generic Gentoo copyright, GPL2-or-later applies:

    SPDX-License-Identifier: GPL-2+

    Copyright © 2012-2019 Anthony Parsons <ant@flussence.eu>

    This is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.
