The `flussence` overlay for Gentoo
==================================

Some packages I'm using or have used. There's patched versions of other people's
ebuilds, and a few I made myself because they didn't exist anywhere else at the
time.

I try not to add anything with known bugs. If you find an ebuild here that
doesn't compile, or anything that doesn't look like an upstream bug, please
mention it on https://github.com/flussence/ebuilds/issues[this repo's Github
Issues page].

Installing
----------

Put this in your `repos.conf`, then do `emerge --sync flussence`:

    [flussence]
    location = /var/db/repositories/flussence
    sync-type = git
    sync-uri = https://github.com/flussence/ebuilds.git

Contents
--------
`games-server/minecraft-server` — minecraft-server ebuilds::
+
--
These are heavily modified versions of the ebuilds in the
http://git.overlays.gentoo.org/gitweb/?p=proj/java.git;a=summary[Java overlay]
(which hadn't been updated since around 1.4).

The OpenRC initscript was removed as I'm not using it any more and can't vouch
for its usability. Versions are slotted so you can have any number of major
versions and snapshots installed at the same time.
--

`gnome-extra/gucharmap` — GTK+2 gucharmap::
A good character map program (much nicer than KCharSelect, which is a Windows
clone). The Gentoo ebuild for this is deliberately crippled to try and force you
to install GTK+3, so I wrote a better one from scratch. Make sure to add
`gucharmap::gentoo` to your `package.mask`.

`media-sound/audacious` — GTK+2 audacious media player::
`media-plugins/audacious-plugins` — dependency for audacious::
Temporary ebuilds for https://bugs.gentoo.org/566150.
Will be removed once `audacious-3.7*::gentoo` becomes available.

`media-video/get_iplayer` — Lightweight get_iplayer ebuild::
Imported from another repository (`::ikelos`, iirc). That version had an
unnecessary mplayer dependency, this doesn't. Also has more id3tag support.

`media-video/obs-studio` — https://github.com/jp9000/obs-studio[OBS Studio]::
Builds OBS from Git. Probably has too many `USE` flags, but it works.

`net-irc/irssi` — Riced irssi ebuilds::
+
--
Tweaked `irssi::gentoo` ebuilds; stable version with optional DANE and 256-color
terminal support, and a git ebuild with far too many USE flags.

Avoid using anything but the 256-color support for now; `USE=dane` in particular
will build fine but crash at runtime.
--

`sys-apps/kmscon` — kmscon 8::
`dev-libs/libtsm` — kmscon 8's dependency::
Anti-aliased bloat for your consoles. Works but feels slightly buggy to me.

`sys-process/runit` — My own rewrite of the Gentoo runit ebuild::
+
--
Supports separate-root-and-usr partitions and kexec rebooting. Solid and
reliable; exists because upstream's ebuild wasn't.

Take a look at https://github.com/flussence/runit-scripts[my runit-scripts
repository] for replacements to some OpenRC initscripts. *DO NOT* file bugs on
Gentoo sites about either those nor the ebuild, as I've unfortunately noticed
some people doing.
--

`x11-misc/tint2` — slightly more up to date tint2 ebuild::
tint2 moved from Google Code to GitLab a long time ago and released new versions
fairly recently. This addresses both.


[NOTE]
.Boilerplate headers and copyright attribution
================================================================================
The 3-line legalese header on each ebuild is required to be present, verbatim,
by Gentoo's QA programs. Other than the GPL-2 statement, the rest of it should
not be relied on as legally valid. Correct attribution for sources can be found
in the git logs or this document.

Reference:
https://devmanual.gentoo.org/ebuild-writing/common-mistakes/index.html
================================================================================
