The `flussence` overlay for Gentoo
==================================

Some packages I'm using or have used. There's patched versions of other people's
ebuilds, and a few I made myself because they didn't exist anywhere else at the
time.

I try not to add anything with known bugs. If you find an ebuild here that
doesn't compile, or anything that doesn't look like an upstream bug, please
mention it on https://github.com/flussence/ebuilds/issues[this repo's Github
Issues page].

Requires an EAPI 5 (or higher) package manager.

Installing
----------

This is for modern versions of Portage. If you don't have that, it's assumed you
already know what you're doing.

    # cd /etc/portage; mkdir repos.conf && cat > repos.conf/flussence.conf
    [flussence]
    location = /var/db/repositories/flussence
    sync-type = git
    sync-uri = https://github.com/flussence/ebuilds.git
    ^D
    # emerge --sync flussence

Contents
--------
`dev-java/java-config-wrapper` — java-config-wrapper without the hardcoded Portage deps::
+
--
Modernized versions of Gentoo's Java scripts to play nice with other package
managers, like `perl-cleaner` and `python-updater` already do. Doesn't
support pkgcore yet; I'll add it if someone sends a patch.

Fixes these upstream bugs:

* https://bugs.gentoo.org/193305
* https://bugs.gentoo.org/504124
* https://bugs.gentoo.org/505098
--

`games-server/minecraft-server` — Maintained minecraft-server ebuilds::
`games-server/minecraft-common` — dependency for minecraft-server::
These are heavily modified versions of the ebuilds in the
http://git.overlays.gentoo.org/gitweb/?p=proj/java.git;a=summary[Java overlay]
(which hadn't been updated since around 1.4). These support running from custom
directories and don't spawn/depend on tmux (recent versions of the game support
rcon).

`gnome-extra/gucharmap` — GTK+2 gucharmap::
A good character map program (much nicer than KCharSelect, which is a Windows
clone). The Gentoo ebuild for this is deliberately crippled to try and force you
to install GTK+3, so I wrote a better one from scratch. Make sure to add
`gucharmap::gentoo` to your `package.mask`.

`media-sound/audacious` — GTK+2 audacious media player::
`media-plugins/audacious-plugins` — dependency for audacious::
+
--
Temporary ebuilds from https://bugs.gentoo.org/538414 (with fix in comment 4
applied). Will be removed once `audacious-3.6*::gentoo` becomes available.

Yes, upstream went back to GTK+2.

_#suddenoutbreakofcommonsense_
--

`media-video/get_iplayer` — Lightweight get_iplayer ebuild::
Imported from another repository (`::ikelos`, iirc). That version had an
unnecessary mplayer dependency, this doesn't. Also has more id3tag support.

`net-irc/irssi` — Riced irssi ebuilds::
+
--
Tweaked `irssi::gentoo` ebuilds; stable version with optional DANE and 256-color
terminal support, and a git ebuild with far too many USE flags.

Avoid using anything but the 256-color support for now; `USE=dane` in particular
will build fine but crash at runtime.
--

`sys-apps/kmscon` — kmscon 8::
`dev-libs/libtsm` — kmscon 8's dependency::
Anti-aliased bloat for your consoles. Works but feels slightly buggy to me.

`sys-process/runit` — My own rewrite of the Gentoo runit ebuild::
+
--
Supports separate-root-and-usr partitions and kexec rebooting. Solid and
reliable; exists because upstream's ebuild wasn't.

Take a look at https://github.com/flussence/runit-scripts[my runit-scripts
repository] for replacements to some OpenRC initscripts. *DO NOT* file bugs on
Gentoo sites about either those nor the ebuild, as I've unfortunately noticed
some people doing.
--


[NOTE]
.Boilerplate headers and copyright attribution
================================================================================
The 3-line legalese header on each ebuild is required to be present, verbatim,
by Gentoo's QA programs. Other than the GPL-2 statement, the rest of it should
not be relied on as legally valid. Correct attribution for sources can be found
in the git logs or this document.

Reference:
https://devmanual.gentoo.org/ebuild-writing/common-mistakes/index.html
================================================================================
