Some ebuilds for Gentoo
=======================

Packages for things that:
aren't in the main tree at all,
aren't as up-to-date as I'd like there,
or where the official ebuilds deviate too much from vanilla for my liking.

I try not to add anything with known bugs,
but be aware this is a personal, opinionated set of ebuilds
and there's no plans to push things back to gentoo.git.
Feel free to report issues if you want,
or even to add these things to Gentoo yourself.

You may also be interested in
https://gitlab.com/flussence/perl6-overlay[my perl6 ebuilds] or
https://gitlab.com/flussence/runit-scripts[my runit-scripts repository].

Installing
----------

Put this in your `repos.conf`, then do `emerge --sync flussence`:

    [flussence]
    location = /var/db/repositories/flussence
    sync-type = git
    sync-uri = https://gitlab.com/flussence/overlay.git

Contents
--------
N.B. anything not listed here is considered temporary,
and may be removed at any time.

`app-crypt/signify` — https://github.com/aperezdc/signify[OpenBSD Signify]::
Signify is a strong cryptographic signature tool that fits on a floppy disk, with public
keys that fit in 140 characters, and a manpage that fits on one screen.

`dev-libs/libsass` — https://github.com/sass/libsass[libsass]::
`dev-util/sassc` — https://github.com/sass/sassc[SassC]::
C++ implementation of SASS stylesheet preprocessor.
The perl5 CSS::Sass is too broken to package as an ebuild so I use this instead now.

`dev-vcs/src` — https://gitlab.com/esr/src[Simple Revision Control]::
A version control tool suitable for all those loose scripts you have lying around.

`games-server/minecraft-server` — minecraft-server ebuilds::
+
--
These are heavily modified versions of the ebuilds in the
http://git.overlays.gentoo.org/gitweb/?p=proj/java.git;a=summary[Java overlay]
(which hadn't been updated since around 1.4).

The OpenRC initscript was removed and versions are individually slotted;
it's up to you to decide how you want to run a game server.
--

`gnome-extra/gucharmap` — GTK+2 gucharmap::
A good character map program (nicer than KCharSelect, which is a Windows clone).
The Gentoo ebuild for this is GTK+3-only for no good reason,
so I wrote a better one from scratch that respects the user's choice.
Make sure to add `gucharmap::gentoo` to your `package.mask`.
Caveat: only supports old versions of Unicode. I may try to fix this.

`media-video/obs-studio` — https://github.com/jp9000/obs-studio[OBS Studio]::
Builds OBS from Git.
Probably has too many `USE` flags, but it works and does what I need from it.
You can even build it with no GUI at all, if you're into that sort of thing.

`net-p2p/go-ipfs-bin` — Updated versions of Gentoo IPFS ebuilds::
The in-tree one is 5 versions behind as of this writing, proxy-maintainer seems to not care.

`sys-process/runit` — My own rewrite of the Gentoo runit ebuild::
+
--
Supports separate-root-and-usr partitions and kexec rebooting.
Solid and reliable; exists because Gentoo's ebuild wasn't.

For replacements to some OpenRC initscripts, take a look at
https://gitlab.com/flussence/runit-scripts[my runit-scripts repository].
--

[NOTE]
.Boilerplate headers and copyright attribution
================================================================================
The 2-line legalese header on each ebuild is required to be present, verbatim,
by Gentoo's “repoman” QA tool.
Other than the GPL-2 statement, the rest of it should not be considered valid.
Correct attribution for sources can be found in the git logs or this document.

Reference:
https://devmanual.gentoo.org/ebuild-writing/common-mistakes/index.html
================================================================================
