#!/bin/sh
# /etc/runit/1 - system one-time tasks
#
# This file runs OpenRC up to the "boot" runlevel to get your system into a
# reasonable state. If you need to add system-specific one-shot tasks, consider
# using OpenRC's existing /etc/local.d/ facility via the boot runlevel instead
# of editing this file.

PATH=/sbin:/usr/sbin:/bin:/usr/bin

RUNLEVEL=S /sbin/rc sysinit
RUNLEVEL=S /sbin/rc boot

# Spawn a login prompt if "single" is passed on the boot command line.
case " $(</proc/cmdline) " in
    *" single "* )
        /sbin/rc single
        /sbin/sulogin
    ;;
esac

# Runit decides whether to shutdown or reboot based on statting these files (and
# making them symlinks doesn't work). In the worst case, having the rootfs
# wedged read-only, you'll end up with a poweroff instead of a reboot.
for file in reboot stopit; do
    install -m 000 /dev/null /etc/runit/$file
done
