#!/bin/sh
# /etc/runit/1 - system one-time tasks
#
# This file runs OpenRC up to the "boot" runlevel to get your system into a
# reasonable state. If you need to add system-specific one-shot tasks, consider
# using OpenRC's existing /etc/local.d/ facility via the boot runlevel instead
# of editing this file, as it will be overwritten on upgrades.

SVDIR=/etc/service
PATH=/sbin:/usr/sbin:/bin:/usr/bin

RUNLEVEL=S /sbin/openrc sysinit
RUNLEVEL=S /sbin/openrc boot

# Spawn a login prompt if "single" is passed on the boot command line.
read -r kcmdline </proc/cmdline
case " $kcmdline " in
    *" single "* )
        /sbin/openrc single
        /sbin/sulogin
        exit 100
    ;;
esac

# Runit expects $SVDIR to be mutable, which isn't good to do in /etc/ for a
# number of good reasons, but is hard to change due to compatibility reasons.
# We try here to symlink the $SVDIR/**/supervise/ dirs to /run/ so that the
# system still works if the filesystem $SVDIR's on is (or becomes) readonly.
tmpstate="/run/runit"

# This may fail if /run/ also isn't writable, but that's not a fatal error on
# its own.
install -m 0755 -d "$tmpstate" || exit 0

# Attempt to symlink each $sv's ./supervise/ (resp. ./log/supervise/) directory
# to /run/runit/$sv/ (resp. /run/runit/log.$sv/) in order to minimise filesystem
# writes in /etc/.
# If the supervise directories are already symlinks, they'll be left alone.
for sv in "$SVDIR"/*/; do
    if [ ! -L "$sv"/supervise ]; then
        rm -rfv "$sv"/supervise
        ln -Trs "$tmpstate"/"${sv##*/}" "$sv"/supervise
    fi

    if [ -d "$sv"/log ] && [ ! -L "$sv"/log/supervise ]; then
        rm -rfv "$sv"/log/supervise
        ln -Trs "$tmpstate"/log."${sv##*/}" "$sv"/log/supervise
    fi
done

# Do the same for shutdown control files.
# In the worst case (the filesystem these reside on being wedged read-only)
# you'll still be able to poweroff, just not reboot.
for fn in reboot stopit; do
    [ -L /etc/runit/$fn ] && continue
    rm -fv /etc/runit/$fn
    ln -Trs "$tmpstate"/$fn /etc/runit/$fn
done
