#!/bin/sh

SVDIR=/etc/service
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin

# avoid logging to the current tty except as a last resort
for console_device in /dev/{tty12,ttyS1,tty1,console}; do
    if [ -c "${console_device}" ]; then
        exec <>"${console_device}" >"${console_device}" 2>"${console_device}"
        break
    fi
done

exec env - PATH="${PATH}" SVDIR="${SVDIR}" runsvdir -P "${SVDIR}"
