#!/bin/sh

SVDIR=/etc/service
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin

# avoid logging to the current tty except as a last resort
# N.B. openvt is *very* picky about needing the "--".
exec openvt --wait -- env - PATH="${PATH}" SVDIR="${SVDIR}" runsvdir -P "${SVDIR}"
