#!/bin/sh
# /etc/runit/3 - system shutdown tasks

exec >/dev/console 2>&1
PATH=/sbin:/usr/sbin:/bin:/usr/bin
stty sane

# This will work with any service with "getty" in its name,
# in case you decide not to use the provided agetty scripts.
# If you're logged in on a tty somewhere this will return false,
# giving you some extra time to finish whatever you were doing.
echo 'Shutting down login consoles...'
sv shutdown /etc/service/*getty*

echo 'Stopping remaining services...'
sv shutdown /etc/service/* || {
    echo 'Some services refused to stop. Killing them in 30 seconds.'
    sv -w 30 force-shutdown /etc/service/*
}

# If kexec is in a runnable state, this will cause it to do the reboot.
# If not, it'll just fall through here and runit will do so itself.
echo 'Doing OpenRC shutdown sequence...'
if test -x /etc/runit/reboot; then
    RUNLEVEL=6 /sbin/openrc reboot
    kexec -e
else
    RUNLEVEL=0 /sbin/openrc shutdown
fi
