#!/bin/sh

PATH=/bin:/usr/bin
MSG="System is going down for reboot in 14 seconds..."

cd /etc/runit
touch stopit reboot
chmod 100 stopit reboot \
    && echo "$MSG" | $(type -p wall || echo "busybox wall")
/bin/sleep 14
