#!/bin/sh
# Early mount some virtual filesystems we use:
# /proc/cmdline is needed to check for the boot param "single".
# /sys/fs/cgroup/runit.{1..3} is for organisation and cleanup.
while read -r src tgt type opts; do
    mount --source "${src}" --target "${tgt}" --type "${type}" --options "${opts}"
done <<FSTAB
proc /proc proc gid=10,hidepid=invisible
sysfs /sys sysfs defaults
cgroup2 /sys/fs/cgroup cgroup2 memory_recursiveprot,memory_hugetlb_accounting
FSTAB
