#!/bin/sh

# /proc/cmdline is used by 10-emergency-shell to check for boot param "single"
# /sys/fs/cgroup/runit.{1..3} is used by 01-confine-processes
# /run/runit is used by 60-create-run-runit

cat <<FSTAB |
proc /proc proc nodev,noexec,nosuid
tmpfs /run tmpfs mode=0755,nodev,noexec,nosuid,nr_inodes=1M,size=32M,strictatime
sysfs /sys sysfs nodev,noexec,nosuid
cgroup2 /sys/fs/cgroup cgroup2
FSTAB
while read -r src tgt type opts; do
    mount --options "${opts}" --source "${src}" --target "${tgt}" --type "${type}"
    # Try to apply /etc/fstab on top of the options specified here. This may
    # fail noisily if a target isn't present in fstab, but it isn't fatal.
    mount --options remount "${tgt}" 2>/dev/null || :
done
