#!/bin/sh
# Spawn a recovery shell if the situation calls for it.

if mountpoint -q /proc; then
    read -r boot_cmdline </proc/cmdline
    case " ${boot_cmdline} " in
        *" single "* )
            echo "'single' keyword present in boot params" ;;
        * )
            exit 0 ;;
    esac
else
    echo "/proc was not mounted when it was expected"
fi

cat <<EOF
***
Starting an emergency shell. After exit, the system will attempt to reboot.
To skip that reboot and attempt to resume the normal boot process,
delete the file "${runsv_runtime_dir}/reboot" before exiting the shell.
***
EOF

openrc single

install -m 0100 /dev/null "${runsv_runtime_dir}/reboot"
/sbin/sulogin --timeout=100

[ -f "${runsv_runtime_dir}/reboot" ] && exit 100
